### PR TITLE
#152 support value classes

### LINKED ISSUE #152: Feature: inline classes
I am trying to use Kotlin's experimental `inline class` feature. I have an interface with a method accepting a parameter with an inline class type. In this case, `every` function throws an exception.

### Prerequisites
My Kotlin version is: 1.3.0-rc-146

- [x] I am running the latest version - 1.8.9.kotlin13
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Expected Behavior

I should be able to define `every` with `any()` in parameters.

### Current Behavior

Test throws an exception.

### Failure Information (for bugs)

See the exception details in Failure logs section.

#### Steps to Reproduce

This is a test case. I am running this with `Kotlin 1.3.0-rc-146`, `kotlin-reflect 1.3.0-rc-146`,  `JUnit 5.1.0`, `mockk 1.8.9.kotlin13`.

``` kotlin
import io.mockk.every
import io.mockk.mockk
import org.junit.jupiter.api.Test

class MockkFailingTest {
    @Test // fails
    fun `mockk test using any()`() {
        val mocked = mockk<TestMock>(relaxed = true)
        every { mocked.test(any()) } returns 1
    }

    @Test // passes
    fun `mockk test using hardcoded value`() {
        val mocked = mockk<TestMock>(relaxed = true)
        every { mocked.test(MyInlineType("123")) } returns 1
    }

}

inline class MyInlineType(val value: String)

interface TestMock {
    fun test(value: MyInlineType): Int
}
```

#### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* MockK version: 1.8.9.kotlin13
* OS: Ubuntu 18.04
* Kotlin version: 1.3.0-rc-146
* JDK version: 1.8
* JUnit version: 5.1.0
* Type of test: unit test

#### Failure Logs

```
io.mockk.MockKException: Failed matching mocking signature for
SignedCall(retValue=0, isRetValueMock=false, retType=class kotlin.Int, self=TestMock(#2), method=test-gNmuAAA(String), args=[null], invocationStr=TestMock(#2).test-gNmuAAA(null))
left matchers: [any()]

	at io.mockk.impl.recording.SignatureMatcherDetector.detect(SignatureMatcherDetector.kt:99)
	at io.mockk.impl.recording.states.RecordingState.signMatchers(RecordingState.kt:38)
	at io.mockk.impl.recording.states.RecordingState.round(RecordingState.kt:30)
	at io.mockk.impl.recording.CommonCallRecorder.round(CommonCallRecorder.kt:45)
	at io.mockk.impl.eval.RecordedBlockEvaluator.record(RecordedBlockEvaluator.kt:47)
	at io.mockk.impl.eval.EveryBlockEvaluator.every(EveryBlockEvaluator.kt:25)
	at io.mockk.MockKDsl.internalEvery(API.kt:93)
	at io.mockk.MockKKt.every(MockK.kt:104)
	at conduit.handler.LoginHandlerImplTest.mockk test(LoginHandlerImplTest.kt:79)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:436)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:115)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$6(TestMethodTestDescriptor.java:170)
	at org.junit.jupiter.engine.execution.ThrowableCollector.execute(ThrowableCollector.java:40)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:166)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:113)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:58)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor$NodeExecutor.lambda$executeRecursively$3(HierarchicalTestExecutor.java:112)
	at org.junit.platform.engine.support.hierarchical.SingleTestExecutor.executeSafely(SingleTestExecutor.java:66)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor$NodeExecutor.executeRecursively(HierarchicalTestExecutor.java:108)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor$NodeExecutor.execute(HierarchicalTestExecutor.java:79)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor$NodeExecutor.lambda$executeRecursively$2(HierarchicalTestExecutor.java:120)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor$NodeExecutor.lambda$executeRecursively$3(HierarchicalTestExecutor.java:120)
	at org.junit.platform.engine.support.hierarchical.SingleTestExecutor.executeSafely(SingleTestExecutor.java:66)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor$NodeExecutor.executeRecursively(HierarchicalTestExecutor.java:108)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor$NodeExecutor.execute(HierarchicalTestExecutor.java:79)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor$NodeExecutor.lambda$executeRecursively$2(HierarchicalTestExecutor.java:120)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor$NodeExecutor.lambda$executeRecursively$3(HierarchicalTestExecutor.java:120)
	at org.junit.platform.engine.support.hierarchical.SingleTestExecutor.executeSafely(SingleTestExecutor.java:66)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor$NodeExecutor.executeRecursively(HierarchicalTestExecutor.java:108)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor$NodeExecutor.execute(HierarchicalTestExecutor.java:79)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:55)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:43)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:170)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:154)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:90)
	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:74)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
```

### LINKED ISSUE #683: kotlin.KotlinNullPointerException error when I try to use any() method on a value class parameter
When I try to use `any()` method on a parameter with a value class as type, I have `kotlin.KotlinNullPointerException` error.

### Expected Behavior

The test should run correctly and the mock can intercept all instance of the value class parameter.

### Current Behavior

Generate a `kotlin.KotlinNullPointerException` error on test execution
I don't have the issue if I replace the value class with data class and I don't have the issue if I replace the `any()` call by a explicit instance of the value class.

#### Steps to Reproduce

See the code below.

#### Context

* MockK version: 1.12.0
* OS: MacOs 11.5.2 (20G95)
* Kotlin version: 1.5.21, 1.5.30
* JDK version: OpenJDK Runtime Environment AdoptOpenJDK-11.0.11+9 (build 11.0.11+9)
* JUnit version: 5.6.2 (if I belived the depencies tree in IntelliJ)
* Kotest version : 4.6.1, 4.6.2
* Type of test: unit test

#### Failure Logs

Please include any relevant log snippets or files here.

#### Stack trace

```
Test failed
kotlin.KotlinNullPointerException
	at io.mockk.impl.recording.states.RecordingState.matcher(RecordingState.kt:53)
	at io.mockk.impl.recording.CommonCallRecorder.matcher(CommonCallRecorder.kt:52)
	at org.test.HelloTest$1$1$1.invoke(HelloTest.kt:22)
	at org.test.HelloTest$1$1$1.invoke(HelloTest.kt:12)
	at io.mockk.impl.eval.RecordedBlockEvaluator$record$block$1.invoke(RecordedBlockEvaluator.kt:25)
	at io.mockk.impl.eval.RecordedBlockEvaluator$enhanceWithRethrow$1.invoke(RecordedBlockEvaluator.kt:78)
	at io.mockk.impl.recording.JvmAutoHinter.autoHint(JvmAutoHinter.kt:23)
	at io.mockk.impl.eval.RecordedBlockEvaluator.record(RecordedBlockEvaluator.kt:40)
	at io.mockk.impl.eval.EveryBlockEvaluator.every(EveryBlockEvaluator.kt:30)
	at io.mockk.MockKDsl.internalEvery(API.kt:92)
	at io.mockk.MockKKt.every(MockK.kt:98)
	at org.test.HelloTest$1$1.invokeSuspend(HelloTest.kt:12)
	at org.test.HelloTest$1$1.invoke(HelloTest.kt)
	at org.test.HelloTest$1$1.invoke(HelloTest.kt)
	at io.kotest.core.internal.ExecutionsKt$executeWithBehaviours$2$1.invokeSuspend(executions.kt:13)
	at io.kotest.core.internal.ExecutionsKt$executeWithBehaviours$2$1.invoke(executions.kt)
	at io.kotest.core.internal.ExecutionsKt$executeWithBehaviours$2$1.invoke(executions.kt)
	at io.kotest.core.internal.ExecutionsKt.wrapTestWithGlobalAssert(executions.kt:39)
	at io.kotest.core.internal.ExecutionsKt.access$wrapTestWithGlobalAssert(executions.kt:1)
	at io.kotest.core.internal.ExecutionsKt$executeWithBehaviours$2.invokeSuspend(executions.kt:12)
	at io.kotest.core.internal.ExecutionsKt$executeWithBehaviours$2.invoke(executions.kt)
	at io.kotest.core.internal.ExecutionsKt$executeWithBehaviours$2.invoke(executions.kt)
	at io.kotest.core.internal.ExecutionsKt$wrapTestWithAssertionModeCheck$2.invokeSuspend(executions.kt:25)
	at io.kotest.core.internal.ExecutionsKt$wrapTestWithAssertionModeCheck$2.invoke(executions.kt)
	at io.kotest.core.internal.ExecutionsKt$wrapTestWithAssertionModeCheck$2.invoke(executions.kt)
	at io.kotest.core.internal.AssertionsCheckKt.executeWithAssertionsCheck(assertionsCheck.kt:25)
	at io.kotest.core.internal.ExecutionsKt.wrapTestWithAssertionModeCheck(executions.kt:24)
	at io.kotest.core.internal.ExecutionsKt.executeWithBehaviours(executions.kt:11)
	at io.kotest.core.internal.TestCaseExecutor$executeInScope$2.invokeSuspend(TestCaseExecutor.kt:268)
	at io.kotest.core.internal.TestCaseExecutor$executeInScope$2.invoke(TestCaseExecutor.kt)
	at io.kotest.core.internal.TestCaseExecutor$executeInScope$2.invoke(TestCaseExecutor.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:89)
	at kotlinx.coroutines.CoroutineScopeKt.coroutineScope(CoroutineScope.kt:264)
	at io.kotest.core.internal.TestCaseExecutor.executeInScope(TestCaseExecutor.kt:262)
	at io.kotest.core.internal.TestCaseExecutor.access$executeInScope(TestCaseExecutor.kt:57)
	at io.kotest.core.internal.TestCaseExecutor$executeAndWait$4$1$1$3$1$1.invokeSuspend(TestCaseExecutor.kt:234)
	at io.kotest.core.internal.TestCaseExecutor$executeAndWait$4$1$1$3$1$1.invoke(TestCaseExecutor.kt)
	at io.kotest.core.internal.TestCaseExecutor$executeAndWait$4$1$1$3$1$1.invoke(TestCaseExecutor.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturnIgnoreTimeout(Undispatched.kt:100)
	at kotlinx.coroutines.TimeoutKt.setupTimeout(Timeout.kt:148)
	at kotlinx.coroutines.TimeoutKt.withTimeout(Timeout.kt:44)
	at io.kotest.core.internal.TestCaseExecutor$executeAndWait$4$1$1$3$1.invokeSuspend(TestCaseExecutor.kt:233)
	at io.kotest.core.internal.TestCaseExecutor$executeAndWait$4$1$1$3$1.invoke(TestCaseExecutor.kt)
	at io.kotest.core.internal.TestCaseExecutor$executeAndWait$4$1$1$3$1.invoke(TestCaseExecutor.kt)
	at io.kotest.engine.ExecutorExecutionContext$executeWithTimeoutInterruption$4.invokeSuspend(ExecutorExecutionContext.kt:77)
	at io.kotest.engine.ExecutorExecutionContext$executeWithTimeoutInterruption$4.invoke(ExecutorExecutionContext.kt)
	at io.kotest.engine.ExecutorExecutionContext$executeWithTimeoutInterruption$4.invoke(ExecutorExecutionContext.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:89)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:165)
	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
	at io.kotest.engine.ExecutorExecutionContext.executeWithTimeoutInterruption(ExecutorExecutionContext.kt:75)
	at io.kotest.core.internal.TestCaseExecutor$executeAndWait$4$1$1$3.invokeSuspend(TestCaseExecutor.kt:232)
	at io.kotest.core.internal.TestCaseExecutor$executeAndWait$4$1$1$3.invoke(TestCaseExecutor.kt)
	at io.kotest.core.internal.TestCaseExecutor$executeAndWait$4$1$1$3.invoke(TestCaseExecutor.kt)
	at io.kotest.mpp.ReplayKt.replay(replay.kt:18)
	at io.kotest.core.internal.TestCaseExecutor$executeAndWait$4$1$1.invokeSuspend(TestCaseExecutor.kt:227)
	at io.kotest.core.internal.TestCaseExecutor$executeAndWait$4$1$1.invoke(TestCaseExecutor.kt)
	at io.kotest.core.internal.TestCaseExecutor$executeAndWait$4$1$1.invoke(TestCaseExecutor.kt)
	at io.kotest.engine.ExecutorExecutionContext$executeWithTimeoutInterruption$4.invokeSuspend(ExecutorExecutionContext.kt:77)
	at io.kotest.engine.ExecutorExecutionContext$executeWithTimeoutInterruption$4.invoke(ExecutorExecutionContext.kt)
	at io.kotest.engine.ExecutorExecutionContext$executeWithTimeoutInterruption$4.invoke(ExecutorExecutionContext.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:89)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:165)
	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
	at io.kotest.engine.ExecutorExecutionContext.executeWithTimeoutInterruption(ExecutorExecutionContext.kt:75)
	at io.kotest.core.internal.TestCaseExecutor$executeAndWait$4$1.invokeSuspend(TestCaseExecutor.kt:220)
	at io.kotest.core.internal.TestCaseExecutor$executeAndWait$4$1.invoke(TestCaseExecutor.kt)
	at io.kotest.core.internal.TestCaseExecutor$executeAndWait$4$1.invoke(TestCaseExecutor.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturnIgnoreTimeout(Undispatched.kt:100)
	at kotlinx.coroutines.TimeoutKt.setupTimeout(Timeout.kt:148)
	at kotlinx.coroutines.TimeoutKt.withTimeout(Timeout.kt:44)
	at io.kotest.core.internal.TestCaseExecutor$executeAndWait$4.invokeSuspend(TestCaseExecutor.kt:219)
	at io.kotest.core.internal.TestCaseExecutor$executeAndWait$4.invoke(TestCaseExecutor.kt)
	at io.kotest.core.internal.TestCaseExecutor$executeAndWait$4.invoke(TestCaseExecutor.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:89)
	at kotlinx.coroutines.SupervisorKt.supervisorScope(Supervisor.kt:57)
	at io.kotest.core.internal.TestCaseExecutor.executeAndWait(TestCaseExecutor.kt:215)
	at io.kotest.core.internal.TestCaseExecutor.invokeTestCase(TestCaseExecutor.kt:184)
	at io.kotest.core.internal.TestCaseExecutor.executeActiveTest(TestCaseExecutor.kt:153)
	at io.kotest.core.internal.TestCaseExecutor.access$executeActiveTest(TestCaseExecutor.kt:57)
	at io.kotest.core.internal.TestCaseExecutor$intercept$innerExecute$1$1.invokeSuspend(TestCaseExecutor.kt:89)
	at io.kotest.core.internal.TestCaseExecutor$intercept$innerExecute$1$1.invoke(TestCaseExecutor.kt)
	at io.kotest.core.internal.TestCaseExecutor$intercept$innerExecute$1$1.invoke(TestCaseExecutor.kt)
	at io.kotest.core.internal.TestCaseExecutor.executeIfEnabled(TestCaseExecutor.kt:117)
	at io.kotest.core.internal.TestCaseExecutor.access$executeIfEnabled(TestCaseExecutor.kt:57)
	at io.kotest.core.internal.TestCaseExecutor$intercept$innerExecute$1.invokeSuspend(TestCaseExecutor.kt:89)
	at io.kotest.core.internal.TestCaseExecutor$intercept$innerExecute$1.invoke(TestCaseExecutor.kt)
	at io.kotest.core.internal.TestCaseExecutor$intercept$innerExecute$1.invoke(TestCaseExecutor.kt)
	at io.kotest.core.internal.TestCaseExecutor.intercept(TestCaseExecutor.kt:103)
	at io.kotest.core.internal.TestCaseExecutor.execute(TestCaseExecutor.kt:69)
	at io.kotest.engine.spec.runners.SingleInstanceSpecRunner.runTest(SingleInstanceSpecRunner.kt:104)
	at io.kotest.engine.spec.runners.SingleInstanceSpecRunner.access$runTest(SingleInstanceSpecRunner.kt:34)
	at io.kotest.engine.spec.runners.SingleInstanceSpecRunner$execute$interceptAndRun$2$4.invokeSuspend(SingleInstanceSpecRunner.kt:57)
	at io.kotest.engine.spec.runners.SingleInstanceSpecRunner$execute$interceptAndRun$2$4.invoke(SingleInstanceSpecRunner.kt)
	at io.kotest.engine.spec.runners.SingleInstanceSpecRunner$execute$interceptAndRun$2$4.invoke(SingleInstanceSpecRunner.kt)
	at io.kotest.engine.launchers.SequentialTestLauncher$launch$3$1$1.invokeSuspend(SequentialTestLauncher.kt:22)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

#### Minimal reproducible code (the gist of this issue)

```kotlin
plugins {
    kotlin("jvm") version "1.5.21"
}

group = "org.example"
version = "1.0-SNAPSHOT"

repositories {
    mavenCentral()
}

dependencies {
    implementation(kotlin("stdlib"))
    testImplementation("io.kotest:kotest-runner-junit5:4.6.1")
    testImplementation("io.mockk:mockk:1.12.0")
}
```
```kotlin
package org.test

@JvmInline
value class Name(val value: String)

interface Printer {
    fun print(name: Name): String
}

class Hello(private val printer: Printer) {
    fun hello(name: String) {
        println(printer.print(Name(name)))
    }
}
```
```kotlin
package org.test

import io.kotest.core.spec.style.ShouldSpec
import io.mockk.every
import io.mockk.mockk

class HelloTest : ShouldSpec({
    val mockPrinter = mockk<Printer>()

    should("print message") {
        every { mockPrinter.print(any()) } returns "OK"

        val hello = Hello(mockPrinter)

        hello.hello("TEST")
    }

})
```

### LINKED ISSUE #791: KotlinNullPointerException when using capture() for an inline class parameter
### Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Expected Behavior

When using **capture()** for an **inline class parameter** it should work.

### Current Behavior

A _KotlinNullPointerException_ is raised and it's impossible to check the value passed as parameter

#### Steps to Reproduce

_(See the code below)_
1. Create an inline class **A** in Kotlin
2. Create a class **B** that use the **A** as parameter of a method
3. Create a test and capture() the parameter of the method

#### Context

* MockK version: 1.12.2
* OS: Windows
* Kotlin version: 1.6.0
* JDK version: 11
* JUnit version: 4.13.2
* Type of test: unit test

#### Stack trace

```
// -----------------------[ YOUR STACK STARTS HERE ] -----------------------
kotlin.KotlinNullPointerException
	at io.mockk.impl.recording.states.RecordingState.matcher(RecordingState.kt:53)
	at io.mockk.impl.recording.CommonCallRecorder.matcher(CommonCallRecorder.kt:52)

	at io.mockk.impl.eval.RecordedBlockEvaluator$record$block$1.invoke(RecordedBlockEvaluator.kt:25)
	at io.mockk.impl.eval.RecordedBlockEvaluator$enhanceWithRethrow$1.invoke(RecordedBlockEvaluator.kt:78)
	at io.mockk.impl.recording.JvmAutoHinter.autoHint(JvmAutoHinter.kt:23)
	at io.mockk.impl.eval.RecordedBlockEvaluator.record(RecordedBlockEvaluator.kt:40)
	at io.mockk.impl.eval.EveryBlockEvaluator.every(EveryBlockEvaluator.kt:30)
	at io.mockk.MockKDsl.internalEvery(API.kt:93)
	at io.mockk.MockKKt.every(MockK.kt:98)
// -----------------------[ YOUR STACK TRACE ENDS HERE ] -----------------------
```

#### Minimal reproducible code (the gist of this issue)

```kotlin
// -----------------------[ YOUR CODE STARTS HERE ] -----------------------
//THE INLINE CLASS
@JvmInline
value class InlineClass(val value : String)

//THE SERVICE
class InlineService {

    fun test(inlineClass: InlineClass) {
       //do stuff
     }

}

//THE TEST
class InlineServiceTest {

    private val inlineService =  mockk<InlineService>()
    val inlineClasses = mutableListOf<InlineClass>()
    
    @Test
    fun test() {
      //Call multiple times the test method

      every { inlineService.test(capture(inlineClasses)) } returns ...
      //Nullpointer raised on the line before

      assertEquals(5, inlineClasses.size)
    }
}
// -----------------------[ YOUR CODE ENDS HERE ] -----------------------
```

### PR DESCRIPTION
**Pull request by aSemy**
Update: 

`any()` and `slot()` now support value classes! 

Summary 

* Added new 'expect' functions for 'unboxing' a value class to get its internal type, and to 'wrap' an object instance within a value class.
* refactored `RecordingState` matcher to account for value classes
* refactored the `SignatureValueGenerator` jvm impl to recursively generate values for value classes

resolves #152 
resolves #791
resolves #683

---

This PR will hopefully provide some support for value classes #152 

WIP - just some failing tests at the moment (credit to @qoomon)

~This PR is blocked at the moment because the Kotlin language level is set to 1.4 - see #850~ MockK is now on language level 1.5 🎉

### CODE REVIEW

**Comment by Raibaz** [comment]
I'm fine with upgrading Kotlin to 1.7.0 by default, just make sure we maintain backwards compatibility at least to a couple versions back, i.e. we can drop support to 1.4.* if needed but I'd keep at least support to 1.5.*.

**Comment by aSemy** [comment]
Okay, I think I've cracked the code.

A quick summary:

To fix slots, `TypedMatcher` needs to account for value classes

```kotlin
/**
 * Checks if argument is of specific type
 */
interface TypedMatcher {
    val argumentType: KClass<*>

    fun checkType(arg: Any?): Boolean {
        return when {
            argumentType.simpleName === null -> true
            argumentType.isValue             -> {
                val unboxedClass = InternalPlatformDsl.unboxClass(argumentType)
                return unboxedClass.isInstance(arg)
            }
            else                             -> argumentType.isInstance(arg)
        }
    }
}
```

And to handle matching stubs to invocations, `JvmSignatureValueGenerator` also needs to account for value classes.

```kotlin
class JvmSignatureValueGenerator(val rnd: Random) : SignatureValueGenerator {
    override fun <T : Any> signatureValue(
        cls: KClass<T>,
        anyValueGeneratorProvider: () -> AnyValueGenerator,
        instantiator: AbstractInstantiator,
    ): T {

        if (cls.isValue) {
            val valueCls = InternalPlatformDsl.unboxClass(cls)
            val valueSig = signatureValue(valueCls, anyValueGeneratorProvider, instantiator)

            val constructor = cls.primaryConstructor!!.apply { isAccessible = true }
            return constructor.call(valueSig)
        }

        return cls.cast(
            when (cls) {
                java.lang.Boolean::class -> rnd.nextBoolean()
                java.lang.Byte::class -> rnd.nextInt().toByte()
                java.lang.Short::class -> rnd.nextInt().toShort()
                java.lang.Character::class -> rnd.nextInt().toChar()
                java.lang.Integer::class -> rnd.nextInt()
                java.lang.Long::class -> rnd.nextLong()
                java.lang.Float::class -> rnd.nextFloat()
                java.lang.Double::class -> rnd.nextDouble()
                java.lang.String::class -> rnd.nextLong().toString(16)

                else ->
                    @Suppress("UNCHECKED_CAST")
                    anyValueGeneratorProvider().anyValue(cls, isNullable = false) {
                        instantiator.instantiate(cls)
                    } as T
            }
        )
    }
}
```

In order to do this I created a common function on `InternalPlatformDsl`, and in JVM implemented it using the code from `ValueClassSupport.kt`

```kotlin
actual object InternalPlatformDsl {

    // ...

    actual fun unboxClass(cls: KClass<*>): KClass<*> {
        if (!cls.isValue) return cls

        // get backing field
        val backingField = cls.valueField()

        // get boxed value
        return backingField.returnType.classifier as KClass<*>
    }
}
```


I'll commit what I have. I think there are some edgecases if a value class' value is also a value class. 

The test coverage for value classes is very low - basically every MockK API operation should verify it is compatible with value classes.

**Review by qoomon — APPROVED** [review]

**Review by qoomon — APPROVED** [review]

File: dsl/jvm/src/main/kotlin/io/mockk/InternalPlatformDsl.kt [hunk 1]
```diff
@@ -232,3 +257,26 @@ class JvmCoroutineCall<T>(private val lambda: suspend () -> T) : CoroutineCall<T
         }
     }
 }
+
+// TODO this is copy-pasted from ValueClassSupport
+//      I will try to move that class so it's available here
```
Comment (aSemy) [inline dsl/jvm/src/main/kotlin/io/mockk/InternalPlatformDsl.kt:262]: I'm not sure how to resolve this.

* `ValueClassSupport.kt` is in project `mockk-agent-jvm`
* `InternalPlatformDsl` is in project `mockk-dsl-jvm`

I'm looking for suggestions. Maybe it's okay just to have it copy and pasted?

File: dsl/jvm/src/main/kotlin/io/mockk/InternalPlatformDsl.kt [hunk 2]
```diff
@@ -232,3 +257,26 @@ class JvmCoroutineCall<T>(private val lambda: suspend () -> T) : CoroutineCall<T
...
+        // ...and exactly one constructor parameter
+        val constructorParameter = constructor.parameters.first()
+        // ...with a backing field
+        val backingField = declaredMemberProperties
+            .first { it.name == constructorParameter.name }
+            .apply { isAccessible = true }
+
+        backingField
+    } as KProperty1<out T, *>
+}
```
Comment (aSemy) [inline dsl/jvm/src/main/kotlin/io/mockk/InternalPlatformDsl.kt:281]: I'm not sure how to resolve this.

* `ValueClassSupport.kt` is in project `mockk-agent-jvm`
* `InternalPlatformDsl` is in project `mockk-dsl-jvm`

I'm looking for suggestions. Maybe it's okay just to have it copy and pasted?

Comment (Raibaz) [reply dsl/jvm/src/main/kotlin/io/mockk/InternalPlatformDsl.kt:281]: yep i think if they are in those two separate modules there's no better way and we can live with it being copypasted.

**Comment by Raibaz** [comment]
Thanks a lot for putting this together!

I'll take a look early next week.

File: dsl/jvm/src/main/kotlin/io/mockk/InternalPlatformDsl.kt (hunk 2 above)
Comment (qoomon) [reply dsl/jvm/src/main/kotlin/io/mockk/InternalPlatformDsl.kt:281]: I think a comment where the same functionality is implemented would help, i case that code ever needs to be updated.

Comment (aSemy) [reply dsl/jvm/src/main/kotlin/io/mockk/InternalPlatformDsl.kt:281]: Good idea, and I've made an issue to try and de-duplicated it later #857

**Comment by aSemy** [comment]
There's a bug. I tried adding a test case for #729, but it causes MockK to hang indefinitely! 

```kotlin
    /** https://github.com/mockk/mockk/issues/729 */
    @Test
    fun `verify extension function with UInt return can be stubbed`() {

        val fn = mockk<String.() -> UInt>()

        every { "string".fn() } returns 777u

        val result = "string".fn()

        assertEquals(777u, result)
    }
```

**Comment by qoomon** [comment]
I think we can reduce the code of `ValueClassSupport`, have look at
```kotlin
package me.qoomon.enhancements.kotlin

import kotlin.reflect.KClass
import kotlin.reflect.KProperty1
import kotlin.reflect.full.declaredMemberProperties
import kotlin.reflect.jvm.isAccessible

/**
 * Boxed value. Wrapped value of a value class or self.
 */
val <T : Any> T.boxedValue: Any?
    get() = if (this::class.isValue)
        @Suppress("UNCHECKED_CAST")
        (this::class as KClass<T>).valueProperty().get(this)
    else this

/**
 * Boxed class. Wrapped class of a value class or self.
 */
val KClass<*>.boxedClass: KClass<*>
    get() = if (this::class.isValue)
        this.valueProperty().returnType.classifier as KClass<*>
    else this

@Suppress("UNCHECKED_CAST")
private fun <T : Any> KClass<T>.valueProperty(): KProperty1<T, *> {
    require(isValue) { "$this is not a value class" }
    // value classes always have exactly one property
    return declaredMemberProperties.first().apply { isAccessible = true }
}
```

**Comment by aSemy** [comment]
> I think we can reduce the code of `ValueClassSupport`

Agreed - but `fun <T : Any> KClass<T>.isValueClass()` is necessary because it throws an exception when used from `fun <T : Any> T.boxedValue(): Any?`

**Comment by qoomon** [comment]
Is it the native isValue property that's throwing an exception or my polyfill implemention?

**Comment by qoomon** [comment]
@aSemy I wasn't able to reproduce an exception by calling `.isValue` on a `KFunction` instance

**Comment by qoomon** [comment]
@aSemy there was a bug in my reduced `ValueClassSupport` code in the previous comment. I fixed it already within the comment`. `.boxedClass` needs to check for `if (this.isValue)` instead of `if (this::class.isValue)`

**Comment by qoomon** [comment]
feel free to include my tests 
```kotlin
package me.qoomon.enhancements.kotlin

import org.junit.jupiter.api.Test
import strikt.api.expectThat
import strikt.assertions.isEqualTo

internal class ReflectionsKtTest {

    @Test
    fun getBoxedValue() {
        // given
        val givenObject = Dummy("moin")

        // when
        val boxedValue = givenObject.boxedValue

        // then
        expectThat(boxedValue) isEqualTo givenObject.value
    }

    @Test
    fun getBoxedClass() {
        // given
        val givenObject = Dummy("moin")

        // when
        val boxedClass = givenObject::class.boxedClass

        // then
        expectThat(boxedClass) isEqualTo givenObject.value::class
    }

    @JvmInline
    value class Dummy(val value: String)
}
```

**Comment by qoomon** [comment]
@aSemy regarding `isValueClass()` I think we can get rid of this method in favour of do the try catch within the `.isValue` polyfill 
```kotlin
/**
 * POLYFILL for kotlin version < 1.5
 * will be shadowed by implementation in kotlin SDK 1.5+
 *
 * @return true if this is an inline class, else false
 */
private val <T : Any> KClass<T>.isValue: Boolean
    get() = try {
        !isData &&
            primaryConstructor?.parameters?.size == 1 &&
            java.declaredMethods.any { it.name == "box-impl" }
    } catch (_: UnsupportedOperationException) {
        false
    }
```

**Comment by qoomon** [comment]
this version of `ValueClassSupport` should work. All tests are running locally
```kotlin
package io.mockk

import kotlin.reflect.KClass
import kotlin.reflect.KProperty1
import kotlin.reflect.full.declaredMemberProperties
import kotlin.reflect.jvm.isAccessible

/**
 * Underlying property value of a **`value class`** or self
 */
val <T : Any> T.boxedValue: Any?
    @Suppress("UNCHECKED_CAST")
    get() = if (!this::class.isValue) this
    else (this::class as KClass<T>).boxedProperty.get(this)

/**
 * Underlying property class of a **`value class`** or self
 */
val KClass<*>.boxedClass: KClass<*>
    get() = if (!this.isValue) this
    else this.boxedProperty.returnType.classifier as KClass<*>

/**
 * Underlying property of a **`value class`**
 */
private val <T : Any> KClass<T>.boxedProperty: KProperty1<T, *>
    get() = if (!this.isValue_safe) throw UnsupportedOperationException("$this is not a value class")
    // value classes always have exactly one property
    else this.declaredMemberProperties.first().apply { isAccessible = true }

private val <T : Any> KClass<T>.isValue_safe: Boolean
    get() = try {
        this.isValue
    } catch (_: Throwable) {
        false
    }
```

**Comment by qoomon** [comment]
@aSemy please find my PR https://github.com/aSemy/mockk/pull/1

**Review by qoomon — APPROVED** [review]

**Comment by aSemy** [comment]
Thanks @qoomon! Merged in, and I made some minor tweaks. 

I also added some more tests for nested value classes - I'll disable them for now because they can be handled in a later PR.

However the local-extension function tests need to be resolved - they cause MockK to go into an infinite loop. Even if there's a way to make MockK throw an exception and say "this isn't supported yet" - is that possible?

**Comment by aSemy** [comment]
The issue with tests like this

https://github.com/aSemy/mockk/blob/592bdaf710e1be674742afa61147dfad584d6072/mockk/common/src/test/kotlin/io/mockk/it/ValueClassTest.kt#L385-L410

failing is that value classes are handled inconsistently in MockK. 

For example, if I comment out this line (or another one like it, I can't remember exactly)

https://github.com/aSemy/mockk/blob/592bdaf710e1be674742afa61147dfad584d6072/agent/android/src/main/kotlin/io/mockk/proxy/android/advice/Advice.kt#L84

then the extension function tests work

It's hard to keep track of all of the entry and exit points of MockK's stubbing and mocking and such. 

---

I think a proper fix to this is to create a new internal `KClassData` type. 

Whenever MockK has to handle a `KClass`, it needs to determine if it's a value class or not. If it's not, then no problem, continue as normal. Else, create a wrapper for the value class that can recursively unwrap the actual type (the one the compiler sees) and also wrap instances.

Creating a new type for this would ensure consistent behaviour across MockK.

```kotlin
sealed interface KClassData<T> {
  val cls: KClass<T>

  /** A regular [KClass] - treat as normal */
  @JvmInline
  value class Cls<T>(
    override val cls: KClass<T>
  ) : KClassData<T>
  
  data class ValueClass<T, E>(
    override val cls: KClass<T>,
  ): KClassData<T> {
    val unwrappedType: KClass<E> = ...
    
    fun wrap(any: Any?): T = // recursively wrap

    fun unwrap(instance: T): E = // recursively unwrap
  }
}
```

I'm not going to do it in this ticket - just throwing out ideas. It would be a big refactor.

**Comment by aSemy** [comment]
@qoomon @Raibaz can you cancel the checks? I think they're stuck. I don't want to burn through all your GitHub Action hours :)

File: build.gradle [hunk 3]
```diff
@@ -44,4 +46,8 @@ subprojects { subProject ->
             languageVersion = "1.5"
         }
     }
+
+    tasks.withType(Test).configureEach {
+        timeout.set(Duration.ofMinutes(2))
+    }
```
Comment (aSemy) [inline build.gradle:52]: I added this timeout for all test tasks - I think 2 minutes should be fine.

Comment (aSemy) [inline build.gradle:52]: I added this timeout to prevent the tests from hanging. I think 2 minutes should be fine.

Comment (qoomon) [reply build.gradle]: 😎👍

**Review by qoomon — APPROVED** [review]

File: build.gradle (hunk 3 above)
Comment (Raibaz) [reply build.gradle]: Nice, thanks!

**Comment by Raibaz** [comment]
Thanks a lot to both of you for looking so deep into this!

I'll review the code over the next days.

**Comment by qoomon** [comment]
Thank you for this great project.

**Comment by Raibaz** [comment]
Ok, this is really cool, thanks a lot!

Merging this as soon as the build finishes.

**Comment by danieldisu** [comment]
Thank you!

**Comment by dybarsky** [comment]
Thank you @Raibaz

**Comment by qoomon** [comment]
@Raibaz I would have liked to be mentioned in the release changelog as well 😅.

**Comment by Raibaz** [comment]
Damn you're right, sorry!

I edited the changelog.

**Comment by maciejtulaza** [comment]
hey, I still notice issues with `any()` and `value class`es.

I described two problems I found here: https://github.com/mockk/mockk/issues/847#issuecomment-1200129731

Not sure if this is related to this issue, but I encountered it because I first had the issue described here, then upgraded the version of MockK, error was gone but another two came up to life 😅

**Comment by qoomon** [comment]
@aSemy I think I found the bug causing `Duration` and `Result` errors. 
Because `declaredMemberProperties` includes properties without backing fields as well just `.first()` is not sufficient . We need to add following filter `.first { it.javaField != null }`
```kotlin
private val <T : Any> KClass<T>.boxedProperty: KProperty1<T, *>
        get() = if (!this.isValue_safe) {
            throw UnsupportedOperationException("$this is not a value class")
        } else {
            // value classes always have exactly one property with a backing field
            this.declaredMemberProperties.first { it.javaField != null }.apply { isAccessible = true }
        }
```

**Comment by qoomon** [comment]
I'll create a PR this evening.

**Comment by qoomon** [comment]
Have a look at https://github.com/mockk/mockk/pull/872

**Comment by milgner** [comment]
Just ran into this issue today. Method definition:

```
@JvmInline
value class ConnectorType(val name: String) {
    override fun toString() = name
}

@JvmInline
@Serializable
value class DataSourceId(@Serializable(with = UUIDSerializer::class) val id: UUID) {
    override fun toString() = id.toString()
}

class Supervisor() {
    suspend fun createSource(connectorInfo: ConnectorType, dataSourceId: DataSourceId) = either {
        //...
    }
}
```

These are both very straightforward and look like they should be matched with the current implementation.
However, the following test code

```
        val supervisor = mockk<Supervisor>()
        val dataSourceId = slot<DataSourceId>()
        val response = createSourceResponse { status = SupervisorOuterClass.StatusCode.OK }.right()
        
        coEvery {
            supervisor.createSource(TestConnector.TYPE, capture(dataSourceId))
        } returns response
```

produces

```
io.mockk.MockKException: Failed matching mocking signature for
SignedCall(retValue=, isRetValueMock=true, retType=class arrow.core.Either, self=Supervisor(#2), method=createSource-vYlXMxg(String, UUID, Continuation), args=[test, 00000000-0000-0000-0000-000000000000, Continuation at io.redigital.spectre.data_source.AddDataSourceTest$1$1$1.invokeSuspend(AddDataSourceTest.kt:34)], invocationStr=Supervisor(#2).createSource-vYlXMxg(test, 00000000-0000-0000-0000-000000000000, continuation {}))
left matchers: [slotCapture<DataSourceId>()]
```

Changing the parameter types to non-value-classes makes things work as expected.

mockk version: 1.13.8
Kotlin Version 1.9.21
