### PR TITLE
Fix #273 infinite loop when concurrentHashMap is spied

### LINKED ISSUE #273: Bug: spying a ConcurrentMap causes a stack overflow
### Current Behavior

When I try:
```kotlin
val testRestrictionCache = spyk(ConcurrentHashMap<String, Restriction>()).apply {
                put("key", restriction)
            }
// and
verify {
    testRestrictionCache["key"]
    realRepo wasNot Called
}
```

### Failure Information (for bugs)

```Exception in thread "pool-2-thread-1" java.lang.StackOverflowError
    at java.lang.Class.privateGetDeclaredMethods(Class.java:2695)
    at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
    at java.lang.Class.getMethod0(Class.java:3018)
    at java.lang.Class.getMethod(Class.java:1784)
    at java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:936)
    at io.mockk.proxy.jvm.dispatcher.JvmMockKWeakMap.get(JvmMockKWeakMap.java:17)
    at io.mockk.proxy.jvm.advice.BaseAdvice.handler(BaseAdvice.kt:15)
    at java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:936)
    at io.mockk.proxy.jvm.dispatcher.JvmMockKWeakMap.get(JvmMockKWeakMap.java:17)
    at io.mockk.proxy.jvm.advice.BaseAdvice.handler(BaseAdvice.kt:15)
    at java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:936)
    at io.mockk.proxy.jvm.dispatcher.JvmMockKWeakMap.get(JvmMockKWeakMap.java:17)
    at io.mockk.proxy.jvm.advice.BaseAdvice.handler(BaseAdvice.kt:15)
    at java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:936)
    at io.mockk.proxy.jvm.dispatcher.JvmMockKWeakMap.get(JvmMockKWeakMap.java:17)
    at io.mockk.proxy.jvm.advice.BaseAdvice.handler(BaseAdvice.kt:15)
    at java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:936)
    at io.mockk.proxy.jvm.dispatcher.JvmMockKWeakMap.get(JvmMockKWeakMap.java:17)
    at io.mockk.proxy.jvm.advice.BaseAdvice.handler(BaseAdvice.kt:15)
    at java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:936)
    at io.mockk.proxy.jvm.dispatcher.JvmMockKWeakMap.get(JvmMockKWeakMap.java:17)
    at io.mockk.proxy.jvm.advice.BaseAdvice.handler(BaseAdvice.kt:15)
    at java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:936)
    at io.mockk.proxy.jvm.dispatcher.JvmMockKWeakMap.get(JvmMockKWeakMap.java:17)
    at io.mockk.proxy.jvm.advice.BaseAdvice.handler(BaseAdvice.kt:15)
    at java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:936)
    at io.mockk.proxy.jvm.dispatcher.JvmMockKWeakMap.get(JvmMockKWeakMap.java:17)
    at io.mockk.proxy.jvm.advice.BaseAdvice.handler(BaseAdvice.kt:15)
    at java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:936)
...```

#### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* MockK version: 1.9
* OS: Linux Mint
* Kotlin version: 1.3.21
* JDK version: 1.8
* JUnit version: Using most recent version of KotlinTest
* Type of test: unit test

### PR DESCRIPTION
**Pull request by senioroman4uk**
Fix infinite loop when concurrent hashmap is spied. Discovered that abstract map mocking is not working. Should fix #273

### CODE REVIEW

**Comment by oleksiyp** [comment]
Hi, always cool to receive such contributions. Not everybody manages to compile and understand all the internals. Did you run the whole test suite?

**Comment by senioroman4uk** [comment]
I have some problems with cmake on my machine. I will try running it again today

**Comment by senioroman4uk** [comment]
After some struggling with the build (tests do not work on jdk > 8 because of old jacoco version). On my branch I have 9 failed tests. On master (not the latest one, the one that I've based on)

Master:
Screenshot 2020-05-23 at 13 16 21

my branch:
Screenshot 2020-05-23 at 13 19 43

**Comment by senioroman4uk** [comment]
Hi, any concerns regarding this CR?

File: agent/jvm/src/main/kotlin/io/mockk/proxy/jvm/advice/BaseAdvice.kt [hunk 1]
```diff
@@ -42,6 +43,16 @@ internal open class BaseAdvice(
         return handler?.call()
     }
 
+    override fun isMock(instance: Any): Boolean {
+        // in order to avoid endless checks when concurrent hashmap is mocked we need to exclude handlers map explicitly
+        val castedHandlers = handlers as? JvmMockKWeakMap
```
Comment (waterpoweredmonkey) [inline agent/jvm/src/main/kotlin/io/mockk/proxy/jvm/advice/BaseAdvice.kt:48]: Suggestion: Rather than couple `BaseAdvice` with `JvmMockKWeakMap` and adding the isMock method to `JvmMockKDispatcher`, could `fun isMock(instance:Any): Boolean` be provided by an interface? If the handler is of that interface type we can then delegate the check to the handler 'MaybeMockk` implemenation?

`return (handlers as? MaybeMockK)?.isMock(instance) ?: instance !== handlers && handlers.containsKey(instance)`

Note* Take the suggestion `MaybeMockk` with a pinch of salt, a name was needed for the interface in the moment :)

File: agent/jvm/src/main/java/io/mockk/proxy/jvm/dispatcher/JvmMockKWeakMap.java [hunk 2]
```diff
@@ -9,30 +9,30 @@
 import java.util.concurrent.ConcurrentHashMap;
 
 public class JvmMockKWeakMap<K, V> implements Map<K, V> {
-    private final Map<Object, V> map = new ConcurrentHashMap<Object, V>();
+    private final Map<Object, V> target = new ConcurrentHashMap<Object, V>();
```
Comment (waterpoweredmonkey) [inline agent/jvm/src/main/java/io/mockk/proxy/jvm/dispatcher/JvmMockKWeakMap.java:12]: Nit* Renaming variable seems unnecessary even if `getTarget` is the desired name for the method which returns the backing field

Comment (senioroman4uk) [reply agent/jvm/src/main/java/io/mockk/proxy/jvm/dispatcher/JvmMockKWeakMap.java:12]: Well I have based on a naming that is applied in mockito. Having a map with inner property map sounds strange. Target or innerMap sound more appropriate

File: agent/jvm/src/main/kotlin/io/mockk/proxy/jvm/advice/BaseAdvice.kt (hunk 1 above)
Comment (senioroman4uk) [reply agent/jvm/src/main/kotlin/io/mockk/proxy/jvm/advice/BaseAdvice.kt:48]: Hi, somehow missed email notification for your comments. I will try to implement your suggestion.

File: agent/jvm/src/main/java/io/mockk/proxy/jvm/dispatcher/JvmMockKWeakMap.java (hunk 2 above)
Comment (senioroman4uk) [reply agent/jvm/src/main/java/io/mockk/proxy/jvm/dispatcher/JvmMockKWeakMap.java:12]: Please check the latest commit. I have introduced  MockHandlerMap (Map with isMock method), just to decouple map implementation. Maybe I have misunderstood your suggestion, this way baseAdvise delegates isMock to inner map

File: agent/jvm/src/main/kotlin/io/mockk/proxy/jvm/advice/BaseAdvice.kt (hunk 1 above)
Comment (senioroman4uk) [reply agent/jvm/src/main/kotlin/io/mockk/proxy/jvm/advice/BaseAdvice.kt]: Screenshot 2020-08-04 at 22 30 15

File: agent/jvm/src/main/java/io/mockk/proxy/jvm/dispatcher/JvmMockKWeakMap.java (hunk 2 above)
Comment (senioroman4uk) [reply agent/jvm/src/main/java/io/mockk/proxy/jvm/dispatcher/JvmMockKWeakMap.java:12]: Tests results 
Screenshot 2020-08-04 at 22 30 15

File: agent/jvm/src/main/kotlin/io/mockk/proxy/jvm/advice/BaseAdvice.kt (hunk 1 above)
Comment (senioroman4uk) [reply agent/jvm/src/main/kotlin/io/mockk/proxy/jvm/advice/BaseAdvice.kt]: Please check the latest commit. I have introduced MockHandlerMap (Map with isMock method), just to decouple map implementation. Maybe I have misunderstood your suggestion, this way baseAdvise delegates isMock to an inner map.
Test results (same as were prior refactoring)
Screenshot 2020-08-04 at 22 30 15

@ waterpoweredmonkey

**Comment by senioroman4uk** [comment]
Could someone re-review this PR please?

**Comment by senioroman4uk** [comment]
Can anyone re-review?

File: mockk/jvm/src/test/kotlin/io/mockk/jvm/HashMapMockTest.kt [hunk 3]
```diff
@@ -0,0 +1,28 @@
...
+    @Test
+    fun concurrentHashMap_shouldBeSpied_Successfully() {
+        val map = spyk(ConcurrentHashMap<String, String>())
+        assertDoesNotThrow { map.put("key", "value")  }
+
+        verify(exactly = 1) { map.put("key", "value") }
+    }
+
+    @Test
+    @Disabled(value = "mocking of abstractMap don't work")
```
Comment (Raibaz) [inline mockk/jvm/src/test/kotlin/io/mockk/jvm/HashMapMockTest.kt:21]: Not sure if we want to keep this in the codebase disabled as a reference or remove it altogether, what do you think?

Comment (senioroman4uk) [reply mockk/jvm/src/test/kotlin/io/mockk/jvm/HashMapMockTest.kt:21]: I would keep it. Then we can look at the issue and enable the test

Comment (Raibaz) [reply mockk/jvm/src/test/kotlin/io/mockk/jvm/HashMapMockTest.kt:21]: Fine with me. Can you please just add a comment on why it's disabled?

**Comment by MonteCreasor** [comment]
This problem still exists in version 1.10.2. Is it ever going to be fixed?

**Comment by senioroman4uk** [comment]
1.10.2 is to old, it should be fixed in      1.11.0 1.10.6
